--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/3/2022 12:17:38 AM
-- Server version: 8.0.30
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO `misa.web08.nsdh.dxloc`.positions(PositionId, PositionCode, PositionName, CreateDate, CreateBy, ModifiedDate, ModifiedBy) VALUES
('11fbda18-5d9f-396c-1299-04b3a3d51ef2', 'P003', 'Vị trí 003', '2021-03-06 09:34:07', '8UOX1GP80VCA8CP063HA09VS', '2022-06-09 20:36:04', 'Hoàng Thái Bằng '),
('5ada22d3-3248-6596-6e1a-bb545470e80c', 'P001', 'Vị trí 001', '2021-07-24 07:58:12', '1NH', '2022-03-24 23:37:58', 'Nguyễn Văn Ngọc '),
('5e6695e2-5aad-3241-6c1a-bb545470e80c', 'P008', 'Vị trí 008', '2021-03-05 22:19:47', '3', '2022-09-02 08:46:04', 'Trân Việt Hương '),
('60e226cb-63fb-4363-fc4d-8601bf3d85d8', 'P004', 'Vị trí 004', '2021-01-01 00:01:08', 'T705H0T18O998465K8Y93FG6EG391H6PP5JI', '2022-02-21 20:40:22', 'Nguyễn Việt Ngọc '),
('6207a9a7-3bf9-7288-8565-390639088226', 'P006', 'Vị trí 006', '2021-08-18 22:32:58', '863S3L5G71J8018K47L63LFI110977UF', '2022-01-01 00:01:22', 'Nguyễn Minh Mạnh '),
('697be7ba-1738-6adf-298f-4d82f3a13455', 'P002', 'Vị trí 002', '2021-06-02 02:57:24', '1F8N0V5TWJA65X74PI3EX6LAER979Y3E5VTEWLVOR1K', '2022-01-01 00:00:04', 'Nguyễn Tuấn Bằng '),
('6d81a322-63f0-7270-6d1a-bb545470e80c', 'P007', 'Vị trí 007', '2021-01-01 01:08:43', '85CWN901I03W', '2022-03-23 01:47:43', 'Bùi  Thị Lệ'),
('76598eb0-20b1-664e-8665-390639088226', 'P005', 'Vị trí 005', '2021-09-03 00:54:42', 'O6T89K3HX', '2022-05-18 18:24:34', 'Võ Việt Thanh ');