--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 10/3/2022 12:17:38 AM
-- Server version: 8.0.30
-- Client version: 4.1
--


SET NAMES 'utf8';

INSERT INTO `misa.web08.nsdh.dxloc`.department(DepartmenId, DepartmentCode, DepartmentName, CreatedDate, CreatedBy, ModifiedDate, ModifiedBy) VALUES
('11452b0c-768e-5ff7-0d63-eeb1d8ed8cef', 'D005', 'Phòng Chủ tịch', '2021-08-04 09:05:49', 'Trân Minh Mạnh ', '2022-04-01 09:57:51', 'Nông Tuấn Trường '),
('142cb08f-7c31-21fa-8e90-67245e8b283e', 'D007', 'Phòng Lập trình viên', '2021-06-23 20:39:21', 'Nguyễn Ngọc Hương ', '2022-05-01 12:34:46', 'Lê  Thị Diễm'),
('17120d02-6ab5-3e43-18cb-66948daf6128', 'D003', 'Phòng Thư ký', '2021-07-23 03:36:18', 'Nông Ngọc Trường ', '2022-03-07 00:26:50', 'Trịnh  Thị Hường'),
('4577565a-7e3e-493a-74dd-867949feb8b5', 'D006', 'Phòng Tổng giám đốc', '2021-01-13 02:57:19', 'Trân Thái Thành ', '2022-08-28 14:19:33', 'Nguyễn Thái Thành '),
('469b3ece-744a-45d5-957d-e8c757976496', 'D004', 'Phòng Tiếp khách', '2021-08-07 08:16:29', 'Trân Ngọc Minh ', '2022-08-08 18:02:10', 'Nguyễn Ngọc Cường '),
('4e272fc4-7875-78d6-7d32-6a1673ffca7c', 'D008', 'Phòng Bảo vệ', '2021-01-01 01:19:23', 'Trân Ngọc Bằng ', '2022-07-20 13:31:49', 'Nông Minh Hoàng '),
('7686595d-16d5-33b3-0080-e8e2a817c80e', 'D001', 'Phòng Nhân sự', '2021-05-09 11:56:37', 'Hoàng Việt Anh ', '2022-06-02 19:58:23', 'Lê Tuấn Hương '),
('768f8e64-7d10-20c9-967d-e8c757976496', 'D002', 'Phòng Hội thảo', '2021-02-25 07:19:04', 'Nguyễn Văn Ngọc ', '2022-08-16 21:36:55', 'Nông Minh Thái ');